const neostandard = require('neostandard')
const importPlugin = require('eslint-plugin-import')

module.exports = [
  ...neostandard({
    env: ['browser', 'node'],
    globals: {
      $: 'readonly',
      Clusterize: 'readonly',
      Gauge: 'readonly',
      SockJS: 'readonly',
      SvelteComponents: 'readonly',
      THREE: 'readonly',
      Vue: 'readonly',
    },
    ignores: [
      'pug-opts.js',
      'build/**',
      '**/.svelte-kit/**',
      'src/static/js/clusterize.min.js',
      'src/static/js/jquery-1.11.3.min.js',
      'src/static/js/socket.io.js',
      'src/static/js/sockjs.min.js',
      'src/static/js/three.min.js',
      'src/static/js/vue.js',
      'src/svelte-components/dist/**',
    ],
    ts: true,
  }),
  {
    name: 'import/recommended',
    plugins: {
      import: importPlugin,
    },
    rules: importPlugin.flatConfigs.recommended.rules,
  },
  {
    files: ['src/svelte-components/**/*.ts'],
    name: 'import/typescript',
    settings: importPlugin.flatConfigs.typescript.settings,
    rules: {
      ...importPlugin.flatConfigs.typescript.rules,
      'import/no-unresolved': 'off',
      '@typescript-eslint/no-redeclare': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
    },
  },
  {
    linterOptions: {
      reportUnusedDisableDirectives: 'off',
    },
    rules: {
      '@stylistic/array-bracket-spacing': 'warn',
      '@stylistic/comma-spacing': 'warn',
      '@stylistic/eol-last': 'warn',
      '@stylistic/indent': 'warn',
      '@stylistic/key-spacing': 'warn',
      '@stylistic/keyword-spacing': 'warn',
      '@stylistic/multiline-ternary': 'warn',
      '@stylistic/no-multi-spaces': 'warn',
      '@stylistic/no-trailing-spaces': 'warn',
      '@stylistic/object-curly-spacing': 'warn',
      '@stylistic/operator-linebreak': 'warn',
      '@stylistic/padded-blocks': 'warn',
      '@stylistic/quotes': 'warn',
      '@stylistic/semi': 'warn',
      '@stylistic/space-before-blocks': 'warn',
      '@stylistic/space-before-function-paren': 'warn',
      '@stylistic/space-in-parens': 'warn',
      '@stylistic/spaced-comment': 'warn',
      '@stylistic/wrap-iife': 'warn',
      camelcase: 'warn',
      eqeqeq: 'warn',
      'new-cap': 'warn',
      'no-sequences': 'warn',
      'no-undef-init': 'warn',
      'no-unused-expressions': 'warn',
      'no-unused-vars': 'warn',
      'no-useless-computed-key': 'warn',
      'one-var': 'warn',
      'prefer-const': 'warn',
      'prefer-promise-reject-errors': 'warn',
      yoda: 'warn',
    },
  },
]
